name: Update S&P 500 Snapshot History

on:
  schedule:
    - cron: "0 6 * * 1"  # Every Monday at 6 AM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run update script
        run: python backend/scripts/update_snapshots.py

      - name: "Debug: List backend/data directory"
        run: ls -lh backend/data

      - name: Delete existing CSV from release (if exists)
        run: |
          gh auth login --with-token < <(echo "$GH_PAT")
          gh release delete-asset v1.0.0 sp500_snapshot_history.csv -y || echo "No asset to delete"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Upload updated file to release
        run: |
          gh auth login --with-token < <(echo "$GH_PAT")
          if [ -f "backend/data/sp500_snapshot_history.csv" ]; then
            gh release upload v1.0.0 backend/data/sp500_snapshot_history.csv --clobber
          else
            echo "❌ CSV file not found!"
            exit 1
          fi
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
